package com.aurigo.masterworks.testframework.webUI.constants;

public class Constants {

    public final static String LOGIN_PAGE_TITLE = "Masterworks";
    public final static String MAIN_CONTENT_FRAME_NAME = "contentFrame";

    public final static String CONFIG_PROPERTIES_PATH = "src/test/resources/config.properties";
    public final static String TEST_CLASSES_FOLDER_PATH = "target/test-classes/";
    public final static String REPORTS_FOLDER_PATH = "target/Reports/";
    public final static String DEFAULT_DOWNLOAD_PATH = "target/downloads";

    public final static String DEFAULT_LOCATORS_DIRECTORY = "defaultLocators";
    public final static String EMPTY_STRING = "";
    public final static String WF_PENDING_ROLES = "WF_PendingOnRole";
    public final static String EDITED_COLUMN_NAME = "EditedColumnName";
    public final static String TOTAL_SCORE = "TotalScore";
    public final static String AUR_MODIFIED_BY = "AUR_ModifiedBy";
    public final static String ERROR_LOGIN = "User ID/Password is invalid.";
    public final static String BID_LETTING_ERROR = "Item(s) are not approved. Cannot Issue letting.";
    public final static String AUTOGENERATED_TAG = "<Auto Generated>";
    public final static String WORK_ORDER_CODE_STARTING_CONSTANT = "WO_MC_Code";


    /**
     * Document Management
     */
    public final static String UPLOAD_DOCUMENT = "UploadDocument.txt";
    public final static String UPLOAD_INCORRECT_DOCUMENT = "UploadIncorrectDocument.txt";
    public final static String PARENT_FOLDER_NAME = "Parent Folder";

    /**
     * Library
     */
    public final static String INFLATION_RULE_NAME = "Inflation Rule For Test";
    public static final String UPDATED_DOCUMENT_TITLE_NAME = "NewTitle";
    public static final String ADMINISTRATOR_ROLE = "Administrator";
    public static final String HELP_BTN_ERROR_TOAST_MESSAGE = "Select at least one record";
    public static final String STRING_LINK_DOC = "Link Document";
    public static final String STRING_UPLOAD_DOC = "Upload Document";
    public final static String UPLOAD_SUCCESSFUL = "has been uploaded successfully";
    public final static String VENDOR_CATEGORY_TOAST_MESSAGE = "Vendor Category already exists";
    public final static String ERD_WORKINGHOURS_ERROR_MESSAGE = "Working Hours should be > 0 and <= 24 hrs";
    public final static String ERD_EMAILID_ERROR_MESSAGE = "Invalid Email ID";
    public final static String ERD_PHONENO_ERROR_MESSAGE = "Invalid Phone Number";


    /**
     * ERROR Toast Messages
     */
    public final static String AMOUNT_EXCEEDING_ERROR_TOAST = "The Expenses Amount should not be greater than Selected Purchase Order Amount. Request denied.";
    public final static String RATE_ERROR_MESSAGE = "Must be between 0 and 1,000,000,000";
    public final static String RATE_ERROR_MESSAGE_FL = "Must be greater than 0.0000";
    public final static String AGENDA_NO_START_TIME_ERROR_MESSAGE = "Agenda Start time can not be blank. Please enter some value.";

    public final static String AGENDA_NO_END_TIME_ERROR_MESSAGE = "Agenda End time can not be blank. Please enter some value.";
    public final static String AGENDA_WRONG_END_TIME_ERROR_MESSAGE = "Agenda End Time should be greater than Agenda Start time.";
    public final static String MOM_INVITEES_ERROR_MESSAGE = "At least 1 record(s) should be added in the Grid - Meeting Invitees";
    public final static String MOM_TIME_ERROR_MESSAGE = "Meeting End Time should be greater than Meeting Start Time.";
    public final static String NEXT_MEETING_DATE_ERROR_MESSAGE = "Next Meeting Date can not be earlier than Meeting Date.";
    public final static String CONTRACT_ITEM_AMOUNT_EXCEEDING_ERROR = "The value cannot exceed the cost of the Item";
    public final static String PAY_ESTIMATE_QUANTITY_EXCEEDING_ERROR = "Remaining contract amount is less than the remaining Pre payment amount.";
    public final static String PAY_ESTIMATE_AMOUNT_EXCEEDING_ERROR = "Pay Estimate amount cannot be more than contract amount for Item Number";
    public final static String PAY_ESTIMATE_ADJUSTMENT_AMOUNT_EXCEEDING_ERROR = "Total adjustments amount should not be more than the Total Contract Items Amount";
    public final static String PAY_ESTIMATE_UNDO_APPROVE_RECORD_ERROR = "Selected Pay Estimate status can not be un-approved till all Pay Estimate generated after it are un-approved. Please move all such Pay Estimate to draft stage to proceed.";
    public final static String MASTER_CONTRACT_PRICE_DATE_ERROR = "Contract End Date must be greater or equal to Contract Start Date.";
    public final static String WORK_ORDER_REVISION_DATE_ERROR = "Revised Work Order end date should be greater than or equal to current Work order Start date and must be lesser than or equal to Parent Master contract's end date.";
    public final static String NO_ROW_SELECTION_ERROR = "Select at least one record";
    public final static String WORK_ORDER_REVISION_AMOUNT_EXCEEDING_ERROR = "Revised Work order amount cannot be greater than master contract ceiling value.";
    public final static String WORK_ORDER_AMOUNT_EXCEEDING_ERROR = "Work order value cannot be greater than Master contract's ceiling value!";
    public final static String WORK_ORDER_NO_PROJECT_ERROR = "At least 1 record(s) should be added in the Grid - Projects";
    public final static String WORK_ORDER_DATE_ERROR = "Work order End date should be equal to or greater than Start date.";
    public final static String WORK_ORDER_DATE_OUT_OF_MASTER_CONTRACT_RANGE_ERROR = "Work order start date or end date must be within the duration of the selected master contract.";
    public final static String WORK_ORDER_NO_ITEM_ERROR = "Please associate atleast one non zero item.";
    public final static String BUDGET_TEMPLATE_ERROR_ON_ITEMS_CLICK = "\"Please select one record.\"";
    public final static String BUDGET_EXCEL_UPLOAD_ERROR = "\"Please select a file\"";
    public final static String EXTERNAL_IDP_CHANGES_ON_AZURE_ERROR = "Changing the IDP service from AzureAD will disable the AzureAD Bulk Import of Users. User can perform Bulk import through Excel import.";
    public final static String BULK_IMPORT_SUCCESS = "Bulk Import of IDP users is successful";
    public final static String BULK_IMPORT_FAILURE = "Error occurred! Please try retrieving users again. If the problem persists, please contact the Administrator.";
    public final static String WORK_ORDER_REVISION_APPROVE_ERROR = "Work order contract's Change order approval is driven by Work order revision's Approval. Hence cannot be approved manually";
    public final static String CHANGE_ORDER_AMOUNT_EXCEEDING_ERROR = "Revised work order value cannot be greater than master contract ceiling value.";
    public final static String DELETE_CHANGE_ORDER_SELECTION_ERROR = "Please select a Record to delete.";
    public final static String AZURE_LOGIN_ERROR = "Your account or password is incorrect. If you don't remember your password, reset it now.";
    public final static String ADFS_LOGIN_ERROR = "Incorrect user ID or password. Type the correct user ID and password, and try again.";
    public final static String WORK_ORDER_REVISION_PROJECT_UNASSOCIATED_ERROR = "Project(s) must be selected for all items to proceed with work order revision approval.";
    public final static String NO_ROWS_PRESENT = "There are no records to add";
    public final static String CONTAINER_DELETION_ERROR = "Selected container has items in Master Contract, Deletion not allowed";
    public final static String DEFAULT_CONTAINER_DELETION_ERROR = "Selected container has items in either Master Contract or Work Order, Deletion not allowed.";
    public final static String CHANGE_ORDER_REDRAFT_ERROR = "This change order is attached to a work order revision hence cannot be redrafted.";
    public final static String PAY_ESTIMATE_DATE_ERROR = "To Date cannot be less than From Date";
    public final static String PAY_ESTIMATE_GENERATE_ERROR = "To Date has changed since the last time Postings were generated. Please Generate Postings again for the chosen To Date.";
    public final static String PAY_ESTIMATE_RECORD_DELETE_ERROR = "New Pay Estimate has already been generated. Cannot Delete the chosen Pay Estimate. Request Denied.";
    public final static String PAY_ESTIMATE_APPROVE_RECORD_ERROR = "Please Approve the previous Pay Estimate.";
    public final static String FINAL_PAY_ESTIMATE_CONTRACT_VALIDATION_FORMS_ERROR = "To proceed with the creation of Final Pay Estimate , please ensure to take following actions:\n" +
            "-Mark all Contract Items as Complete.";
    public final static String CONTACT_ITEM_ERROR = "At least 1 record(s) should be added in the Grid - Contract Items";
    public final static String MOH_ERROR = "Please select a record.";
    public final static String TRANSMIT_RESPONSE = "submittal response";
    public final static String TRANSMIT_RESPONSE_NO_RECORD = "There is no record in Submittal review section";
    public final static String CEILING_VALUE_ERROR = "Please enter a Ceiling value greater than zero.";
    public final static String SUBPORTFOLIO_TOASTMESSAGE = "This portfolio cannot be deleted as it is part of another portfolio.";
    public final static String Portfolio_Permission_Error = "The selected role does not have permissions to view this page.";
    public final static String SCHEDULE_ADD_TASK = "Changes Saved Successfully!";
    public final static String SCHEDULE_NEGATIVE_DURATION = "Duration value should be greater than zero.";
    public final static String SCHEDULE_EMPTY_UTILIZATION = "Utilization in % must be greater than 0.";
    public final static String RFI_ERROR = "The workflow status of one or more records does not permit delete operation.";
    public final static String RESOURCE_TYPES_EXISTS = "Resource Type already exists";
    public final static String MOH_QUANTITY_EXCEEDING_ERROR = "One or more Items Recovery Quantity is greater than Remaining Quantity. Request Denied.";
    public final static String MOH_RECOVERY_QUANTITY_ERROR = "The recovery quantity that you entered is not within the recovery range.";
    public final static String FUND_RULE_DUPLICATE_NAME_TOAST = "A combination of Rule Name already exists";
    public final static String FUND_RULE_NO_FUND_SOURCE_ERROR = "Fund Rule cannot be saved without fund source distribution details";
    public final static String FUND_RULE_INACTIVE_APPROVAL_ERROR = "In-Active Fund rule cannot be approved!";
    public final static String PROJECT_PUBLISH_ERROR = "Unable to identify published budget estimate, cannot publish the project";
    public final static String MASTER_CONTRACT_REVISION_DATE_ERROR = "Revised contract End Date must be greater or equal to revised Start Date.";
    public final static String MASTER_CONTRACT_AMOUNT_ERROR = "Ceiling value cannot be less than or equal to Zero.";
    public final static String MASTER_CONTRACT_CEILING_AMOUNT_ERROR = "Revised contract ceiling value cannot be less than sum of Work Order values.";
    public final static String MASTER_CONTRACT_WORK_ORDER_DATE_ERROR = "Revised contract Start date cannot be greater than work order Start date.";
    public final static String PURCHASE_ORDER_DATE_ERROR = "End date should be greater than the start date.";
    public final static String INFLATION_RULE_INVALID_RATE = "Please enter Non-Zero value for Inflation Rate";
    public final static String INFLATION_RULE_BOUNDARY_RATE = "Please enter Non-Zero value between -100.00 to 9999.99";
    public final static String INFLATION_RULE_INVALID_RULE = "Invalid Rule ID. Special characters not allowed.";
    public final static String INFLATION_RULE_EXISTS = "Inflation Rule ID already exists";
    public final static String RETRIEVE_MESSAGE = "No Projects meet the specified criteria. Revise the criteria and search again.";
    public final static String PROGRAM_DUPLICATE_NAME_TOAST = "Name already exists";
    public final static String DOCUMENTS_VIEW_TOAST = "Please select a document to view";
    public final static String MULTIPLE_DOCUMENTS_VIEW_TOAST = "Please select only one document to view";
    public final static String DOCUMENTS_DOWNLOAD_TOAST = "Select at least one record";
    public final static String VENDORSCORING_REVIEW_BEFORE_APPROVAL = "The Record can be Approved only from the Details page, as Vendor Scoring needs to be Reviewed before Approval";
    public final static String PROGRAM_BUDGET_ASSOCIATION_MISSING = "There is no Program Budget associated. Request denied";
    public final static String PROGRAM_BUDGET_COST_EXCEEDS_TOAST = "Cumulative Cost of the Project(s) exceeds the Budget.";
    public final static String EMAIL_SUCCESS_TOAST = "Email sent successfully";
    public final static String BUDGET_FORECAST_PREVIEW_TOAST = "Select a single item to preview";
    public final static String DISTRIBUTION_CURVE_EDIT_DELETE_TOAST = "This curve is used in creating project forecast data . Request denied!";

    /**
     * File Upload Toast Message
     */
    public final static String FILE_IMPORT_SUCCESS_MESSAGE = "Records Imported successfully!";

    /**
     * Reports
     */
    public final static String DETAILS_REPORT_NAME = "%s - DETAILS REPORT";
    public final static String LIST_REPORT_NAME = "%s - LIST REPORT";

    /**
     * Excel Import/Export
     */
    public final static String IMPORT_FILE_NAME_BUDGET_ESTIMATE_TYPE = "BudgetEstimateTypeImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_BUDGET_ESTIMATE_ITEMS = "BudgetEstimateItemsImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_BID_LIST = "BidListFile.xlsx";
    public final static String IMPORT_FILE_NAME_BID_ESTIMATE_ITEMS = "BidEstimateItemsImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_Contract_ESTIMATE_ITEMS = "ContractItemsImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_RESOURCE_TITLES_ITEMS = "ResourceTitlesItemsImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_INFLATION_RULES = "InflationRulesImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_USER_DATA = "Users.xlsx";
    public final static String TEMPLATE_FILE_NAME = "%s_Template.xlsx";
    public final static String IMPORT_FILE_NAME_FUND_AGENCY = "FundAgencyImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_FUND_CATEGORIES = "FundCategoriesImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_FUND_TYPE = "FundTypeImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_GLOBAL_FUND_LIST = "GlobalFundListImportFile.xlsx";
    public final static String EXPORT_FILE_NAME_BUDGET_ESTIMATE = "Budget Estimates.xlsx";
    public final static String EXPORT_FILE_NAME_BUDGET_TEMPLATE = "Budget Template.xlsx";
    public final static String IMPORT_FILE_NAME_ITEM_POSTINGXlxs = "ItemPosting.xlsx";
    public final static String IMPORT_FILE_NAME_ITEM_POSTINGXls = "ItemPosting.xls";
    public final static String EXPORT_FILE_NAME_ITEM_POSTING_TemplateXlsx = "Item Posting_Template.xlsx";
    public final static String EXPORT_FILE_NAME_MATERIALS_ON_HANDS = "Materials On Hand.xlsx";
    public final static String EXPORT_FILE_NAME_SECURITY_ROLES_XLS = "Security Roles.xls";
    public final static String EXPORT_FILE_NAME_SECURITY_ROLES_XLSX = "Security Roles.xlsx";
    public final static String EXPORT_FILE_NAME_SECURITY_ROLES_TEMPLATE_XLS = "Security Roles_Template.xls";
    public final static String EXPORT_FILE_NAME_SECURITY_ROLES_TEMPLATE_XLSX = "Security Roles_Template.xlsx";
    public final static String IMPORT_FILE_NAME_SECURITY_ROLES = "SecurityRolesImportFile.xlsx";
    public final static String EXPORT_FILE_NAME_WORK_PROJECTS_XLSX = "Work Projects.xlsx";
    public final static String IMPORT_FILE_NAME_RFI = "Request for Information.xls";
    public final static String IMPORT_FILE_NAME_RFI_XLSX = "Request for Information.xlsx";
    public final static String EXPORT_VENDORS_WITH_DATA_XLSX = "Vendors_Template.xlsx";
    public final static String IMPORT_MASTER_CONTRACT_CATEGORY = "MasterContractCategoryImportFile.xlsx";
    public final static String IMPORT_SCHEDULE = "ScheduleGanttImportFile.xlsx";
    public final static String IMPORT_PURCHASE_ORDER = "PurchaseOrderImportFile.xlsx";
    public final static String IMPORT_PROJECT_PHASES = "ProjectPhaseImportFile.xlsx";
    public final static String IMPORT_RISK_REGISTER = "RiskRegisterImportFile.xlsx";
    public final static String IMPORT_ISSUE_LOG = "IssueLogImportFile.xlsx";
    public final static String IMPORT_FILE_NAME_ENTERPRISE_RESOURCE_DIRECTORY = "EnterpriseResourceDirectory.xlsx";

    public final static String EXPORT_FILE_NAME_BID_XLSX = "Bid Estimate Items_Template.xlsx";
    public final static String EXPORT_FILE_NAME_BID_XLSX_SHEET_NAME = "Item";
    public final static String EXPORT_FILE_NAME_BUDGET_XLSX = "Budget Estimates Items_Template.xlsx";
    public final static String EXPORT_FILE_NAME_BUDGET_XLSX_SHEET_NAME = "Item";
    public final static String EXPORT_FILE_NAME_CONTRACT_XLSX_XML = "Contract Details Items_Template.xlsx";
    public final static String EXPORT_FILE_NAME_CONTRACT_XLSX = "Contract Management Items_Template.xlsx";
    public final static String EXPORT_FILE_NAME_CONTRACT_XLSX_SHEET_NAME = "Item";
    public final static String EXPORT_FILE_NAME_SCHEDULE_XLSX = "ScheduleExport_Template.xlsx";
    public final static String EXPORT_FILE_NAME_SCHEDULE_XLSX_SHEET_NAME = "ScheduleExport";
    public final static String EXPORT_FILE_NAME_SCHEDULE = "ScheduleExport.xlsx";
    public static final String SCHEDULE_EXCEL_IMPORT="ScheduleExcelImportFile.xlsx";

    /**
     * Custom XML Import
     */
    public final static String IMPORT_CUSTOM_FORM_WITH_SHOWINPERMISSIONS_ENABLED = "SHPER01.xml";
    public final static String IMPORT_CUSTOM_FORM_WITH_SHOWINPERMISSIONS_DISABLED = "SHPER00.xml";
    public final static String IMPORT_CUSTOM_FORM_WITH_ERRORS = "ERROR00.xml";
    public final static String IMPORT_CUSTOM_FORM = "SIMPORT.xml";
    public final static String IMPORT_CUSTOM_FORM_FOR_WFVALIDATION = "LIBWFT0.xml";
    public final static String UPLOAD_WF_FOR_CUSTOM_FORM = "WORKFLOW_FOR_LIBWFT0.xoml";
    public final static String UPLOAD_CHECKLIST_WF_FOR_SOQ = "Statement Of Qualification.xoml";

    /**
     * Forecast Toast Message
     */
    public final static String FORECAST_SUCCESSFUL_TOAST_MESSAGE = "Forecast created successfully.";
    public final static String FORECAST_SNAPSHOT_TOAST_MESSAGE = "Forecast snapshot captured.";

    /**
     * Forecast Auto-generated descriptions
     */
    public final static String BUDGET_FORECAST_DESCRIPTION_FOR_PROJECT_FLOW = "Auto generated Budget Planning";
    public final static String BUDGET_FORECAST_DESCRIPTION_FOR_PROGRAM_FLOW = "Auto-generated budget forecast driven by Program approval";

    /**
     * Forecast Snapshot Auto-generated descriptions
     */
    public final static String PROGRAM_FORECAST_SNAPSHOT_DESCRIPTION = "Auto-generated snapshot driven by Forecast Update from Project";

    /**
     * Library data Upload
     */
    public final static String DEFAULT_USERIMPORT_PASSWORD = "Aurigo@1234567";
    public final static String DEFAULT_LIBRARY_PATH = "target/test-classes/LibraryData";

    /**
     * Custom XML File Path
     */
    public final static String DEFAULT_TESTDATA_PATH = "target/test-classes/TestData";

    /**
     * Program Forecast page
     */
    public final static String PROGRAM_FORECAST_PAGE_TOAST_MESSAGE = "Forecst updated successfully.";

    //remote location path for axe rule set js file
    public static final String AXE_RULESET_LOCATION = "https://raw.githubusercontent.com/eBay/accessibility-ruleset-runner/master/rulesets/aXe.ruleset.3.4.0.js";

    //location path for axe rule set js file
    public static String folderPathRuleSet = String.format("%s\\%s", System.getProperty("user.dir"), "src/test/resources/axeRuleset.js");

    public static String DEFAULT_CONTAINER_NAME = "Default";

    /*
    Inflation Rules
     */
    public final static String ANNUAL_RATE_ERROR_MESSAGE = "Please enter Non-Zero value for Inflation Rate";

    /*
    Dynamic Grid
     */
    public final static String DYNAMIC_GRID_FILTERS = "DG_Filters_None.xml";

    /**
     * Administration
     */
    public final static String UPPER_CASE_PASSWORD = "AUTOMATION";
    public final static String LOWER_CASE_PASSWORD = "automation";
    public final static String NON_NUMERIC_CASE_PASSWORD = "Auto@auto";
    public final static String SPECIAL_CHAR_NOT_ALLOWED_PASSWORD = "Auto(auto)";
    public final static String LOWER_CASE_ERROR_MESSAGE = "Length of the password must be at least 6 characters long and it must include\n" +
            "at least one lower case letter.";
    public final static String UPPER_CASE_ERROR_MESSAGE = "Length of the password must be at least 6 characters long and it must include\n" +
            "at least one upper case letter.";
    public final static String NUMERIC_ERROR_MESSAGE = "Length of the password must be at least 6 characters long and it must include\n" +
            "at least one number.";
    public final static String SPECIAL_CHARS_ERROR_MESSAGE = "Length of the password must be at least 6 characters long and it must include\n" +
            "at least one special character. Allowed special characters are ! @ # $ % ^ & * and _ .";
    public final static String PASSWORD_PART_OF_USER_ID_ERROR_MESSAGE = "User ID or part of User ID should not be the part of password.";


    public final static String DYNAMIC_GRID_FILTER_FORM_HEADER_NAME = "DG_Filters_None";
    public final static String DYNAMIC_GRID_FORM_HEADER_COLUMN = "Form Header";

    public final static String MAXIMUM_LOGIN_ATTEMPT_INVALID_VALUE_ERROR_MESSAGE = "Maximum logon attempts should be in the range of 1 and 10..";

    /**
     * Administration to User Management
     */
    public final static String[] USER_ACCOUNTS_PAGE_RIBBON_BUTTONS = {"New", "Edit", "View", "Delete", "Unlock", "Mark Active/InActive", "Reports", "Customize List", "Audit Log", "Excel Import / Export", "--None--", "Manage", "Add", "Clear"};
    public final static String UNSELECTED_ADD_USER_ROLE_ERROR_MESSAGE = "Please select a role from available roles.";
    public final static String UNSELECTED_REMOVE_USER_ROLE_ERROR_MESSAGE = "Please select a role from saved roles.";
    public final static String DUPLICATE_EMAIL_ID_ERROR_MESSAGE = "Please enter a unique Email ID";
    public final static String DUPLICATE_EMAIL_ID_WITHOUT_MANDATORY_DATA_ERROR_MESSAGE = "Please enter valid values for the following fields:\n" +
            "User Name is required.\n" +
            "First Name is required.\n" +
            "Password is required.\n" +
            "Confirm Password is required.\n" +
            "Business Unit is required.";
    public final static String DUPLICATE_USER_ID_ERROR_MESSAGE = "A User with the same User ID already exists. Please enter a different User ID.";
    public final static String EMAIL_ID_INCORRECT_FORMAT_ERROR_MESSAGE = "Please enter valid values for the following fields:\n" +
            "Email (Alphanumeric, format xxx@xxx.xxx)";
    public final static String REGISTER_WITHOUT_MANDATORY_FIELDS_ERROR_MESSAGE = "Please enter valid values for the following fields:\n" +
            "User Name is required.\n" +
            "First Name is required.\n" +
            "Password is required.\n" +
            "Confirm Password is required.\n" +
            "Email is required.";
    public final static String EXPIRY_DATE_EQUAL_LESS_THAN_CURRENT_DATE = "Account expiry date cannot be less than or equal to the current date.Please select a later date.";
    public final static String PASSWORD_MATCH_ERROR_MESSAGE = "Password should match confirmation.";
    public final static String PASSWORD_CHANGE_ERROR_MESSAGE = "New password cannot be same as last 2 password(s).";

    public final static String MANDATORY_FIELDS_WITH_EMAIL = "Please enter valid values for the following fields:\n" +
            "User Name is required.\n" +
            "First Name is required.\n" +
            "Password is required.\n" +
            "Confirm Password is required.";

    public final static String MANDATORY_FIELDS_WITH_EMAIL_AND_PASSWORD = "Please enter valid values for the following fields:\n" +
            "User Name is required.\n" +
            "First Name is required.";
    public final static String USERNAME_MANDATORY_FIELD_ERROR_MESSAGE = "Please enter valid values for the following fields:\n" +
            "User Name is required.";
    public final static String INCORRECT_LOGIN_ERROR_MESSAGE = "Error: Incorrect User Name or Password. 3 attempts remaining.";

    /**
     * Administration to Form Builder
     */
    public final static String FORMID_TOOLTIP = "Form ID should have 7 unique alphanumeric characters";
    public final static String HEADER_TOOLTIP = "Name of the form that will be visible in the UI";
    public final static String PARENTMODULE_TOOLTIP = "The Parent ModuleID of this form.";
    public final static String FOLDER_TOOLTIP = "The folder name where the form will be placed in the navigation tree. Nested folders can be added using a '/' separator to maintain hierarchy. A valid folder path is the one with no leading or trailing '/'";

    public final static String FORMID_ALREADY_EXISTS_ERRORMSG = "FormID - %s already exists. Please ensure that FormID is unique.";
    public final static String FORMID_EMPTY_ERRORMSG = "Please enter a Form ID that has 7 unique alphanumeric characters";
    public final static String FORMHEADER_EMPTY_ERRORMSG = "Please enter header information";

    /**
     * Modules [Key, Value] pairs
     */
    public static String PAY_ESTIMATE_MODULE_ID = "PAYESTM";

    /**
     * Global Fund Documents Upload
     */
    public static String GF_DOCUMENT_1 = "GlobalFundDocument1.txt";
    public static String GF_DOCUMENT_2 = "GlobalFundDocument2.txt";
    public static String CHECK_IN_DOCUMENT = "CheckInDocument.txt";

    /**
     * Alert messages
     */
    public final static String RETRIEVE_PROJECTS_ALERT_MSG = "Data exists in Project grid. Retrieve will override the existing data. Do you want to continue?";

    /**
     * Schedule error
     */
    public final static String CHILD_TASK_ERROR = "Schedule finish date should be before the project end date.";
    public final static String PHASE_TASK_DELETION_ERROR = "Item(s) cannot be removed as project phase is selected.";
    public final static String PHASE_START_DATE_PROJECT_EDIT_ERROR = "Start Date of the Project cannot be after the earliest start date of its phases.";
    public final static String PHASE_END_DATE_PROJECT_EDIT_ERROR = "End Date of the Project cannot be before the latest end date of its phases.";
    public final static String PHASE_DELETION_CONTRACT_ERROR = "cannot be deleted as it is being used in [Contract] item(s).";
    public final static String PHASE_DELETION_SCHEDULE_ERROR = "cannot be deleted as it is being used in [WBS] item(s).";

    /**
     * Master contract error
     */
    public final static String MASTER_CONTRACT_PRICE_LIST_ERROR = "Please associate atleast one price item";
    public final static String EXCEL_EXPORT_NO_DATA_ERROR = "No data to export";
    public final static String BUDGET_ESTIMATE_REPORT_NAME = "BUDGET ESTIMATES";
    public final static String PROJECT_FUND_TRANSACTION_EXCEEDING_ERROR = "The Amount entered is greater than the Remaining amount in Project fund.";

    /**
     * Different format file
     */
    public static final String PDF_FORMAT_FILE = "PdfFormat.pdf";
    public static final String TXT_FORMAT_FILE = "TextFormat.txt";
    public static final String DOC_FORMAT_FILE = "DocumentDocFormat.doc";
    public static final String DOCS_FORMAT_FILE = "DocumentDocxFormat.docx";
    public static final String XLSX_FORMAT_FILE = "XLSXFormat.xlsx";
    public static final String XLS_FORMAT_FILE = "XLSFormat.xls";

    /**
     * FormBuilder xml files
     */
    public static final String DROP_DOWN_MULTIPLE_SELECT_WITHOUT_HIERARCHY = "DropdownTreeMultiSelectWithoutHierarchy.xml";
    public static final String DROP_DOWN_SINGLE_SELECT_WITHOUT_HIERARCHY = "DropdownTreeSingleSelectWithoutHierarchy.xml";

    /**
     * Mail merge Template file
     */
    public static final String MAIL_MERGE_TEMPLATE = "AutomationMailMerge.docx";

    /**
     * Mail merge configure expected error message
     */
    public static final String MAIL_MERGE_CONFIGURE_WITHOUT_VIEW_ERROR="Please Select View.";

    /**
     * Change Order modify existing item to negative value expected error
     */
    public static final String CHANGE_EXISTING_CO_ITEM_QUANTITY_VALUE_TO_NEGATIVE_VALUE="Entered Change in Quantity value makes existing item quantity a negative value. Request denied";

}
